# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RainyShinyCloudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RainyShinyCloudy
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'master'

  target 'RainyShinyCloudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RainyShinyCloudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
